// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: block.proto

package com.tj.proto;

public final class MyBlock {
    private MyBlock() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface BlockHeaderOrBuilder extends
            // @@protoc_insertion_point(interface_extends:block.BlockHeader)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint32 version = 1;</code>
         */
        int getVersion();

        /**
         * <code>uint64 height = 2;</code>
         */
        long getHeight();

        /**
         * <code>uint64 timestamp = 3;</code>
         */
        long getTimestamp();

        /**
         * <code>bytes blockHash = 4;</code>
         */
        com.google.protobuf.ByteString getBlockHash();

        /**
         * <code>bytes previousHash = 5;</code>
         */
        com.google.protobuf.ByteString getPreviousHash();

        /**
         * <code>bytes worldStateRoot = 6;</code>
         */
        com.google.protobuf.ByteString getWorldStateRoot();

        /**
         * <code>bytes transactionRoot = 7;</code>
         */
        com.google.protobuf.ByteString getTransactionRoot();
    }

    /**
     * Protobuf type {@code block.BlockHeader}
     */
    public static final class BlockHeader extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:block.BlockHeader)
            BlockHeaderOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use BlockHeader.newBuilder() to construct.
        private BlockHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private BlockHeader() {
            version_ = 0;
            height_ = 0L;
            timestamp_ = 0L;
            blockHash_ = com.google.protobuf.ByteString.EMPTY;
            previousHash_ = com.google.protobuf.ByteString.EMPTY;
            worldStateRoot_ = com.google.protobuf.ByteString.EMPTY;
            transactionRoot_ = com.google.protobuf.ByteString.EMPTY;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private BlockHeader(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            version_ = input.readUInt32();
                            break;
                        }
                        case 16: {

                            height_ = input.readUInt64();
                            break;
                        }
                        case 24: {

                            timestamp_ = input.readUInt64();
                            break;
                        }
                        case 34: {

                            blockHash_ = input.readBytes();
                            break;
                        }
                        case 42: {

                            previousHash_ = input.readBytes();
                            break;
                        }
                        case 50: {

                            worldStateRoot_ = input.readBytes();
                            break;
                        }
                        case 58: {

                            transactionRoot_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MyBlock.internal_static_block_BlockHeader_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MyBlock.internal_static_block_BlockHeader_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            BlockHeader.class, Builder.class);
        }

        public static final int VERSION_FIELD_NUMBER = 1;
        private int version_;

        /**
         * <code>uint32 version = 1;</code>
         */
        public int getVersion() {
            return version_;
        }

        public static final int HEIGHT_FIELD_NUMBER = 2;
        private long height_;

        /**
         * <code>uint64 height = 2;</code>
         */
        public long getHeight() {
            return height_;
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 3;
        private long timestamp_;

        /**
         * <code>uint64 timestamp = 3;</code>
         */
        public long getTimestamp() {
            return timestamp_;
        }

        public static final int BLOCKHASH_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString blockHash_;

        /**
         * <code>bytes blockHash = 4;</code>
         */
        public com.google.protobuf.ByteString getBlockHash() {
            return blockHash_;
        }

        public static final int PREVIOUSHASH_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString previousHash_;

        /**
         * <code>bytes previousHash = 5;</code>
         */
        public com.google.protobuf.ByteString getPreviousHash() {
            return previousHash_;
        }

        public static final int WORLDSTATEROOT_FIELD_NUMBER = 6;
        private com.google.protobuf.ByteString worldStateRoot_;

        /**
         * <code>bytes worldStateRoot = 6;</code>
         */
        public com.google.protobuf.ByteString getWorldStateRoot() {
            return worldStateRoot_;
        }

        public static final int TRANSACTIONROOT_FIELD_NUMBER = 7;
        private com.google.protobuf.ByteString transactionRoot_;

        /**
         * <code>bytes transactionRoot = 7;</code>
         */
        public com.google.protobuf.ByteString getTransactionRoot() {
            return transactionRoot_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (version_ != 0) {
                output.writeUInt32(1, version_);
            }
            if (height_ != 0L) {
                output.writeUInt64(2, height_);
            }
            if (timestamp_ != 0L) {
                output.writeUInt64(3, timestamp_);
            }
            if (!blockHash_.isEmpty()) {
                output.writeBytes(4, blockHash_);
            }
            if (!previousHash_.isEmpty()) {
                output.writeBytes(5, previousHash_);
            }
            if (!worldStateRoot_.isEmpty()) {
                output.writeBytes(6, worldStateRoot_);
            }
            if (!transactionRoot_.isEmpty()) {
                output.writeBytes(7, transactionRoot_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (version_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, version_);
            }
            if (height_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(2, height_);
            }
            if (timestamp_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(3, timestamp_);
            }
            if (!blockHash_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, blockHash_);
            }
            if (!previousHash_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, previousHash_);
            }
            if (!worldStateRoot_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(6, worldStateRoot_);
            }
            if (!transactionRoot_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(7, transactionRoot_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof BlockHeader)) {
                return super.equals(obj);
            }
            BlockHeader other = (BlockHeader) obj;

            boolean result = true;
            result = result && (getVersion()
                    == other.getVersion());
            result = result && (getHeight()
                    == other.getHeight());
            result = result && (getTimestamp()
                    == other.getTimestamp());
            result = result && getBlockHash()
                    .equals(other.getBlockHash());
            result = result && getPreviousHash()
                    .equals(other.getPreviousHash());
            result = result && getWorldStateRoot()
                    .equals(other.getWorldStateRoot());
            result = result && getTransactionRoot()
                    .equals(other.getTransactionRoot());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getVersion();
            hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHeight());
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestamp());
            hash = (37 * hash) + BLOCKHASH_FIELD_NUMBER;
            hash = (53 * hash) + getBlockHash().hashCode();
            hash = (37 * hash) + PREVIOUSHASH_FIELD_NUMBER;
            hash = (53 * hash) + getPreviousHash().hashCode();
            hash = (37 * hash) + WORLDSTATEROOT_FIELD_NUMBER;
            hash = (53 * hash) + getWorldStateRoot().hashCode();
            hash = (37 * hash) + TRANSACTIONROOT_FIELD_NUMBER;
            hash = (53 * hash) + getTransactionRoot().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static BlockHeader parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BlockHeader parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BlockHeader parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BlockHeader parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BlockHeader parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BlockHeader parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BlockHeader parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static BlockHeader parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static BlockHeader parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static BlockHeader parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static BlockHeader parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static BlockHeader parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(BlockHeader prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code block.BlockHeader}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:block.BlockHeader)
                BlockHeaderOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MyBlock.internal_static_block_BlockHeader_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MyBlock.internal_static_block_BlockHeader_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                BlockHeader.class, Builder.class);
            }

            // Construct using com.tj.proto.MyBlock.BlockHeader.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                version_ = 0;

                height_ = 0L;

                timestamp_ = 0L;

                blockHash_ = com.google.protobuf.ByteString.EMPTY;

                previousHash_ = com.google.protobuf.ByteString.EMPTY;

                worldStateRoot_ = com.google.protobuf.ByteString.EMPTY;

                transactionRoot_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MyBlock.internal_static_block_BlockHeader_descriptor;
            }

            public BlockHeader getDefaultInstanceForType() {
                return BlockHeader.getDefaultInstance();
            }

            public BlockHeader build() {
                BlockHeader result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public BlockHeader buildPartial() {
                BlockHeader result = new BlockHeader(this);
                result.version_ = version_;
                result.height_ = height_;
                result.timestamp_ = timestamp_;
                result.blockHash_ = blockHash_;
                result.previousHash_ = previousHash_;
                result.worldStateRoot_ = worldStateRoot_;
                result.transactionRoot_ = transactionRoot_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof BlockHeader) {
                    return mergeFrom((BlockHeader) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(BlockHeader other) {
                if (other == BlockHeader.getDefaultInstance()) return this;
                if (other.getVersion() != 0) {
                    setVersion(other.getVersion());
                }
                if (other.getHeight() != 0L) {
                    setHeight(other.getHeight());
                }
                if (other.getTimestamp() != 0L) {
                    setTimestamp(other.getTimestamp());
                }
                if (other.getBlockHash() != com.google.protobuf.ByteString.EMPTY) {
                    setBlockHash(other.getBlockHash());
                }
                if (other.getPreviousHash() != com.google.protobuf.ByteString.EMPTY) {
                    setPreviousHash(other.getPreviousHash());
                }
                if (other.getWorldStateRoot() != com.google.protobuf.ByteString.EMPTY) {
                    setWorldStateRoot(other.getWorldStateRoot());
                }
                if (other.getTransactionRoot() != com.google.protobuf.ByteString.EMPTY) {
                    setTransactionRoot(other.getTransactionRoot());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                BlockHeader parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (BlockHeader) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int version_;

            /**
             * <code>uint32 version = 1;</code>
             */
            public int getVersion() {
                return version_;
            }

            /**
             * <code>uint32 version = 1;</code>
             */
            public Builder setVersion(int value) {

                version_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 version = 1;</code>
             */
            public Builder clearVersion() {

                version_ = 0;
                onChanged();
                return this;
            }

            private long height_;

            /**
             * <code>uint64 height = 2;</code>
             */
            public long getHeight() {
                return height_;
            }

            /**
             * <code>uint64 height = 2;</code>
             */
            public Builder setHeight(long value) {

                height_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 height = 2;</code>
             */
            public Builder clearHeight() {

                height_ = 0L;
                onChanged();
                return this;
            }

            private long timestamp_;

            /**
             * <code>uint64 timestamp = 3;</code>
             */
            public long getTimestamp() {
                return timestamp_;
            }

            /**
             * <code>uint64 timestamp = 3;</code>
             */
            public Builder setTimestamp(long value) {

                timestamp_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 timestamp = 3;</code>
             */
            public Builder clearTimestamp() {

                timestamp_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString blockHash_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes blockHash = 4;</code>
             */
            public com.google.protobuf.ByteString getBlockHash() {
                return blockHash_;
            }

            /**
             * <code>bytes blockHash = 4;</code>
             */
            public Builder setBlockHash(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                blockHash_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes blockHash = 4;</code>
             */
            public Builder clearBlockHash() {

                blockHash_ = getDefaultInstance().getBlockHash();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString previousHash_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes previousHash = 5;</code>
             */
            public com.google.protobuf.ByteString getPreviousHash() {
                return previousHash_;
            }

            /**
             * <code>bytes previousHash = 5;</code>
             */
            public Builder setPreviousHash(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                previousHash_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes previousHash = 5;</code>
             */
            public Builder clearPreviousHash() {

                previousHash_ = getDefaultInstance().getPreviousHash();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString worldStateRoot_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes worldStateRoot = 6;</code>
             */
            public com.google.protobuf.ByteString getWorldStateRoot() {
                return worldStateRoot_;
            }

            /**
             * <code>bytes worldStateRoot = 6;</code>
             */
            public Builder setWorldStateRoot(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                worldStateRoot_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes worldStateRoot = 6;</code>
             */
            public Builder clearWorldStateRoot() {

                worldStateRoot_ = getDefaultInstance().getWorldStateRoot();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString transactionRoot_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes transactionRoot = 7;</code>
             */
            public com.google.protobuf.ByteString getTransactionRoot() {
                return transactionRoot_;
            }

            /**
             * <code>bytes transactionRoot = 7;</code>
             */
            public Builder setTransactionRoot(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                transactionRoot_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes transactionRoot = 7;</code>
             */
            public Builder clearTransactionRoot() {

                transactionRoot_ = getDefaultInstance().getTransactionRoot();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:block.BlockHeader)
        }

        // @@protoc_insertion_point(class_scope:block.BlockHeader)
        private static final BlockHeader DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new BlockHeader();
        }

        public static BlockHeader getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<BlockHeader>
                PARSER = new com.google.protobuf.AbstractParser<BlockHeader>() {
            public BlockHeader parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new BlockHeader(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<BlockHeader> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<BlockHeader> getParserForType() {
            return PARSER;
        }

        public BlockHeader getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface BlockOrBuilder extends
            // @@protoc_insertion_point(interface_extends:block.Block)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.block.BlockHeader header = 1;</code>
         */
        boolean hasHeader();

        /**
         * <code>.block.BlockHeader header = 1;</code>
         */
        BlockHeader getHeader();

        /**
         * <code>.block.BlockHeader header = 1;</code>
         */
        BlockHeaderOrBuilder getHeaderOrBuilder();

        /**
         * <code>repeated bytes txs = 2;</code>
         */
        java.util.List<com.google.protobuf.ByteString> getTxsList();

        /**
         * <code>repeated bytes txs = 2;</code>
         */
        int getTxsCount();

        /**
         * <code>repeated bytes txs = 2;</code>
         */
        com.google.protobuf.ByteString getTxs(int index);

        /**
         * <code>bytes extra = 3;</code>
         */
        com.google.protobuf.ByteString getExtra();
    }

    /**
     * Protobuf type {@code block.Block}
     */
    public static final class Block extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:block.Block)
            BlockOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Block.newBuilder() to construct.
        private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Block() {
            txs_ = java.util.Collections.emptyList();
            extra_ = com.google.protobuf.ByteString.EMPTY;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Block(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            BlockHeader.Builder subBuilder = null;
                            if (header_ != null) {
                                subBuilder = header_.toBuilder();
                            }
                            header_ = input.readMessage(BlockHeader.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(header_);
                                header_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                                txs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            txs_.add(input.readBytes());
                            break;
                        }
                        case 26: {

                            extra_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    txs_ = java.util.Collections.unmodifiableList(txs_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MyBlock.internal_static_block_Block_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MyBlock.internal_static_block_Block_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Block.class, Builder.class);
        }

        private int bitField0_;
        public static final int HEADER_FIELD_NUMBER = 1;
        private BlockHeader header_;

        /**
         * <code>.block.BlockHeader header = 1;</code>
         */
        public boolean hasHeader() {
            return header_ != null;
        }

        /**
         * <code>.block.BlockHeader header = 1;</code>
         */
        public BlockHeader getHeader() {
            return header_ == null ? BlockHeader.getDefaultInstance() : header_;
        }

        /**
         * <code>.block.BlockHeader header = 1;</code>
         */
        public BlockHeaderOrBuilder getHeaderOrBuilder() {
            return getHeader();
        }

        public static final int TXS_FIELD_NUMBER = 2;
        private java.util.List<com.google.protobuf.ByteString> txs_;

        /**
         * <code>repeated bytes txs = 2;</code>
         */
        public java.util.List<com.google.protobuf.ByteString>
        getTxsList() {
            return txs_;
        }

        /**
         * <code>repeated bytes txs = 2;</code>
         */
        public int getTxsCount() {
            return txs_.size();
        }

        /**
         * <code>repeated bytes txs = 2;</code>
         */
        public com.google.protobuf.ByteString getTxs(int index) {
            return txs_.get(index);
        }

        public static final int EXTRA_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString extra_;

        /**
         * <code>bytes extra = 3;</code>
         */
        public com.google.protobuf.ByteString getExtra() {
            return extra_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (header_ != null) {
                output.writeMessage(1, getHeader());
            }
            for (int i = 0; i < txs_.size(); i++) {
                output.writeBytes(2, txs_.get(i));
            }
            if (!extra_.isEmpty()) {
                output.writeBytes(3, extra_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (header_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getHeader());
            }
            {
                int dataSize = 0;
                for (int i = 0; i < txs_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(txs_.get(i));
                }
                size += dataSize;
                size += 1 * getTxsList().size();
            }
            if (!extra_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, extra_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Block)) {
                return super.equals(obj);
            }
            Block other = (Block) obj;

            boolean result = true;
            result = result && (hasHeader() == other.hasHeader());
            if (hasHeader()) {
                result = result && getHeader()
                        .equals(other.getHeader());
            }
            result = result && getTxsList()
                    .equals(other.getTxsList());
            result = result && getExtra()
                    .equals(other.getExtra());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasHeader()) {
                hash = (37 * hash) + HEADER_FIELD_NUMBER;
                hash = (53 * hash) + getHeader().hashCode();
            }
            if (getTxsCount() > 0) {
                hash = (37 * hash) + TXS_FIELD_NUMBER;
                hash = (53 * hash) + getTxsList().hashCode();
            }
            hash = (37 * hash) + EXTRA_FIELD_NUMBER;
            hash = (53 * hash) + getExtra().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Block parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Block parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Block parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Block parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Block parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Block parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Block parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Block parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Block parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Block parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Block parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Block parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Block prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code block.Block}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:block.Block)
                BlockOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MyBlock.internal_static_block_Block_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MyBlock.internal_static_block_Block_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Block.class, Builder.class);
            }

            // Construct using com.tj.proto.MyBlock.Block.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (headerBuilder_ == null) {
                    header_ = null;
                } else {
                    header_ = null;
                    headerBuilder_ = null;
                }
                txs_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                extra_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MyBlock.internal_static_block_Block_descriptor;
            }

            public Block getDefaultInstanceForType() {
                return Block.getDefaultInstance();
            }

            public Block build() {
                Block result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Block buildPartial() {
                Block result = new Block(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (headerBuilder_ == null) {
                    result.header_ = header_;
                } else {
                    result.header_ = headerBuilder_.build();
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    txs_ = java.util.Collections.unmodifiableList(txs_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.txs_ = txs_;
                result.extra_ = extra_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Block) {
                    return mergeFrom((Block) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Block other) {
                if (other == Block.getDefaultInstance()) return this;
                if (other.hasHeader()) {
                    mergeHeader(other.getHeader());
                }
                if (!other.txs_.isEmpty()) {
                    if (txs_.isEmpty()) {
                        txs_ = other.txs_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureTxsIsMutable();
                        txs_.addAll(other.txs_);
                    }
                    onChanged();
                }
                if (other.getExtra() != com.google.protobuf.ByteString.EMPTY) {
                    setExtra(other.getExtra());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Block parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Block) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private BlockHeader header_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    BlockHeader, BlockHeader.Builder, BlockHeaderOrBuilder> headerBuilder_;

            /**
             * <code>.block.BlockHeader header = 1;</code>
             */
            public boolean hasHeader() {
                return headerBuilder_ != null || header_ != null;
            }

            /**
             * <code>.block.BlockHeader header = 1;</code>
             */
            public BlockHeader getHeader() {
                if (headerBuilder_ == null) {
                    return header_ == null ? BlockHeader.getDefaultInstance() : header_;
                } else {
                    return headerBuilder_.getMessage();
                }
            }

            /**
             * <code>.block.BlockHeader header = 1;</code>
             */
            public Builder setHeader(BlockHeader value) {
                if (headerBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    header_ = value;
                    onChanged();
                } else {
                    headerBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.block.BlockHeader header = 1;</code>
             */
            public Builder setHeader(
                    BlockHeader.Builder builderForValue) {
                if (headerBuilder_ == null) {
                    header_ = builderForValue.build();
                    onChanged();
                } else {
                    headerBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.block.BlockHeader header = 1;</code>
             */
            public Builder mergeHeader(BlockHeader value) {
                if (headerBuilder_ == null) {
                    if (header_ != null) {
                        header_ =
                                BlockHeader.newBuilder(header_).mergeFrom(value).buildPartial();
                    } else {
                        header_ = value;
                    }
                    onChanged();
                } else {
                    headerBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.block.BlockHeader header = 1;</code>
             */
            public Builder clearHeader() {
                if (headerBuilder_ == null) {
                    header_ = null;
                    onChanged();
                } else {
                    header_ = null;
                    headerBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.block.BlockHeader header = 1;</code>
             */
            public BlockHeader.Builder getHeaderBuilder() {

                onChanged();
                return getHeaderFieldBuilder().getBuilder();
            }

            /**
             * <code>.block.BlockHeader header = 1;</code>
             */
            public BlockHeaderOrBuilder getHeaderOrBuilder() {
                if (headerBuilder_ != null) {
                    return headerBuilder_.getMessageOrBuilder();
                } else {
                    return header_ == null ?
                            BlockHeader.getDefaultInstance() : header_;
                }
            }

            /**
             * <code>.block.BlockHeader header = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    BlockHeader, BlockHeader.Builder, BlockHeaderOrBuilder>
            getHeaderFieldBuilder() {
                if (headerBuilder_ == null) {
                    headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            BlockHeader, BlockHeader.Builder, BlockHeaderOrBuilder>(
                            getHeader(),
                            getParentForChildren(),
                            isClean());
                    header_ = null;
                }
                return headerBuilder_;
            }

            private java.util.List<com.google.protobuf.ByteString> txs_ = java.util.Collections.emptyList();

            private void ensureTxsIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    txs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(txs_);
                    bitField0_ |= 0x00000002;
                }
            }

            /**
             * <code>repeated bytes txs = 2;</code>
             */
            public java.util.List<com.google.protobuf.ByteString>
            getTxsList() {
                return java.util.Collections.unmodifiableList(txs_);
            }

            /**
             * <code>repeated bytes txs = 2;</code>
             */
            public int getTxsCount() {
                return txs_.size();
            }

            /**
             * <code>repeated bytes txs = 2;</code>
             */
            public com.google.protobuf.ByteString getTxs(int index) {
                return txs_.get(index);
            }

            /**
             * <code>repeated bytes txs = 2;</code>
             */
            public Builder setTxs(
                    int index, com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTxsIsMutable();
                txs_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes txs = 2;</code>
             */
            public Builder addTxs(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTxsIsMutable();
                txs_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes txs = 2;</code>
             */
            public Builder addAllTxs(
                    Iterable<? extends com.google.protobuf.ByteString> values) {
                ensureTxsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, txs_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes txs = 2;</code>
             */
            public Builder clearTxs() {
                txs_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString extra_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes extra = 3;</code>
             */
            public com.google.protobuf.ByteString getExtra() {
                return extra_;
            }

            /**
             * <code>bytes extra = 3;</code>
             */
            public Builder setExtra(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                extra_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes extra = 3;</code>
             */
            public Builder clearExtra() {

                extra_ = getDefaultInstance().getExtra();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:block.Block)
        }

        // @@protoc_insertion_point(class_scope:block.Block)
        private static final Block DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Block();
        }

        public static Block getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Block>
                PARSER = new com.google.protobuf.AbstractParser<Block>() {
            public Block parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Block(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Block> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Block> getParserForType() {
            return PARSER;
        }

        public Block getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_block_BlockHeader_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_block_BlockHeader_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_block_Block_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_block_Block_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\013block.proto\022\005block\"\233\001\n\013BlockHeader\022\017\n\007" +
                        "version\030\001 \001(\r\022\016\n\006height\030\002 \001(\004\022\021\n\ttimesta" +
                        "mp\030\003 \001(\004\022\021\n\tblockHash\030\004 \001(\014\022\024\n\014previousH" +
                        "ash\030\005 \001(\014\022\026\n\016worldStateRoot\030\006 \001(\014\022\027\n\017tra" +
                        "nsactionRoot\030\007 \001(\014\"G\n\005Block\022\"\n\006header\030\001 " +
                        "\001(\0132\022.block.BlockHeader\022\013\n\003txs\030\002 \003(\014\022\r\n\005" +
                        "extra\030\003 \001(\014B\032\n\014com.tj.protoB\007MyBlock\210\001\001b" +
                        "\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_block_BlockHeader_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_block_BlockHeader_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_block_BlockHeader_descriptor,
                new String[]{"Version", "Height", "Timestamp", "BlockHash", "PreviousHash", "WorldStateRoot", "TransactionRoot",});
        internal_static_block_Block_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_block_Block_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_block_Block_descriptor,
                new String[]{"Header", "Txs", "Extra",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
